name: Snake GitHub

on:
  workflow_dispatch:  # roda manualmente
  schedule:
    - cron: '0 0 * * *'  # roda 1x por dia

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/snk@v3
        with:
          github_user_name: gabidmag  # seu usuário
          outputs: snake.svg

      - name: Push to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

